title: PMA Communications
email: contact@pmacommunications.com
description: >
  PMA Communications: specialists in producing outstanding event experiences for high level audiences.
logo: "/assets/images/logo.png"
baseurl: ""
url: "https://pmacommunications.com"
paginate:	5 # The number of posts to show per page on your homepage

name: 'Paddy Mirams'
bio: >
  I am Paddy, I am the greatest
author_image: "/assets/images/author.jpg"
# twitter_username: TODO
# github_username:  TODO


markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
